### ISSUE TITLE
How to change or remove the Chinese word beside the block number

### ISSUE THREAD

**Issue by afshinizadi** [iamkun/tower_game#14]
How to change or remove the Chinese word beside the block number, I tried to find it but couldn't find out where is it to change it.

**Comment by iamkun** [comment]
There is a pending PR with English translation might suit your need.

**Comment by git-lt** [comment]
@iamkun 你好，可以留个联系方式吗，我这边有个创业项目不知道你感不感兴趣，主要是小游戏相关的，方便的时候回下，地址在杭州西湖区

**Comment by Free-Guyy** [comment]
just you have to change string name in the main.js which is near gamescore in main.js file. If you get please follow me.
