### ISSUE TITLE
After using hookSpeed the block freezes and doesn't sway

### ISSUE THREAD

**Issue by afshinizadi** [iamkun/tower_game#15]
`hookSpeed: function(currentFloor, currentScore) {
	return currentFloor*10
    }`

I also tried to return a number but again nothing changed and the block just freezes and doesn't sway

**Comment by iamkun** [comment]
Might check this source code and return different number according to currentFloor and currentScore.
https://github.com/bmqb/tower_game/blob/1aa827bc042af3081cc27ed9e00bb26a91f1bea6/src/utils.js#L44
