### ISSUE TITLE
[Documentation] How to customize?

### ISSUE THREAD

**Issue by rubyFeedback** [iamkun/tower_game#23]
Hi there,

Would it be possible to customize the game a little and add instructions how to do so?

For instance, rather than the chinese picture, perhaps allow users another picture,
such as a cat? Another idea for customization could be for users to modify the
colours?

I assume it is all possible to do, but helpful pointers may be nice if you ever have
the time. Thank you for reading!

**Comment by iamkun** [comment]
simply fork the project and do whatever you like 😁
