### ISSUE TITLE
上面的钟摆速度不对啊

### ISSUE THREAD

**Issue by gongjunhao** [iamkun/tower_game#3]

**Comment by iamkun** [comment]
能具体说一下什么问题吗

**Comment by gongjunhao** [comment]
可能你的钟摆频率太快了吧，总感觉你的钟摆速度是匀速的。
在重力和拉力的作用下，在2边最高点应该有暂停的一下，最低端速度最快，也能是帧率不够
我找了几个钟摆的demo
http://newhtml.net/css3-transform-animation-clock-with-pendulum/
http://wow.techbrood.com/fiddle/9739

**Comment by iamkun** [comment]
@gongjunhao 考虑过你说的情况，但是那样游戏就变的太简单了，两边高点速度太慢。

**Comment by Weilor** [comment]
但是这样才真实，目前的效果让我觉得这楼一点重量都没有，轻飘飘的

**Comment by iamkun** [comment]
@Weilor 恩 你说的是另一个问题 下落时候需要有惯性和加速度，才会更真实，这个已经在考虑中了。
