### ISSUE TITLE
可复现bug

### ISSUE THREAD

**Issue by Lijiang0703** [iamkun/tower_game#4]
房子在失败掉落的时候，如果未碰到任何建筑直接掉落，下次摇摆上的房子钩住的位置就会有偏移
![image](https://user-images.githubusercontent.com/15918223/37748631-866828ee-2dbf-11e8-9b11-ace228dd9d29.png)

**Comment by iamkun** [comment]
@Lijiang0703 已更新修复 谢谢反馈 预览链接是CDN可能会有延迟
